export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  ACCOUNT_NOT_ACTIVE: "ACCOUNT_NOT_ACTIVE",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES];